// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package init

import (
	"context"
	"github.com/maybesilent/wire-demo/conf"
	"github.com/maybesilent/wire-demo/consumer"
)

// Injectors from wire.go:

func InitWithDi(ctx context.Context) (*consumer.Consumer, error) {
	config := conf.InitConfig()
	consumerConsumer := consumer.InitConsumer(config)
	return consumerConsumer, nil
}
